[tool.poetry]
name = "personal-assistant"
version = "0.1.0"
description = ""
authors = ["managarmrm1033 <mrtimofei462@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
